function [d_th_dt, d_yw_dt, d_w_th_dt, d_w_yw_dt] = non_linear_model(Vmp, Vmy, th, yw, w_th, w_yw)
    
    l_cm   = 0.015;   % [m] - Distance between the pivot point and the center of mass of the helicopter.
    m_heli = 0.479;   % [kg] - Total moving mass of the helicopter
    J_eq_p = 0.0172;  % [kg-m^2] - Moment of inertia about pitch axis
    J_eq_y = 0.0210;  % [kg-m^2] - Moment of inertia about yaw axis
    g      = 9.81;    % [m/s^2] - Acceleration due to gravity on planet earth
    
    Kpp    = 0.0556;  % [Nm/V] - Torque constant on pitch axis from pitch motor
    Kyy    = 0.21084; % [Nm/V] - Torque constant on yaw axis from yaw motor
    Kpy    = 0.005;   % [Nm/V] - Torque constant on pitch axis from yaw motor
    Kyp    = 0.15;    % [Nm/V] - Torque constant on yaw axis from pitch motor
    Bp     = 0.01;    % [N/V]  - Damping friction factor about pitch axis
    By     = 0.08;    % [N/V]  - Damping friction factor about yaw axis
    
    d_th_dt = w_th;
    d_yw_dt = w_yw;
    d_w_th_dt = (Kpp*Vmp-...
                 Kpy*Vmy-...
                 Bp*w_th-...
                 m_heli*l_cm^2*w_yw^2*sin(th)*cos(th)-...
                 m_heli*g*l_cm*cos(th)) / ...
                (J_eq_p+m_heli*l_cm^2);
    d_w_yw_dt = (Kyp*Vmp-...
                 Kyy*Vmy-...
                 By*w_yw+...
                 2*m_heli*l_cm^2*w_th*w_yw*sin(th)*cos(th)) / ...
                (J_eq_y+m_heli*l_cm^2*cos(th)^2);